unsigned int hex_string_to_int(char msg)
{
// Uses else if statements to convert a Hex value, viewed as a string to an integer for 0 to 99
  unsigned int converted_int;
  if (msg == 0) {converted_int = 0;}
  else if (msg == 1) {converted_int = 1;}
  else if (msg == 2) {converted_int = 2;}
  else if (msg == 3) {converted_int = 3;}
  else if (msg == 4) {converted_int = 4;}
  else if (msg == 5) {converted_int = 5;}
  else if (msg == 6) {converted_int = 6;}
  else if (msg == 7) {converted_int = 7;}
  else if (msg == 8) {converted_int = 8;}
  else if (msg == 9) {converted_int = 9;}
  else if (msg == 16) {converted_int = 10;}
  else if (msg == 17) {converted_int = 11;}
  else if (msg == 18) {converted_int = 12;}
  else if (msg == 19) {converted_int = 13;}
  else if (msg == 20) {converted_int = 14;}
  else if (msg == 21) {converted_int = 15;}
  else if (msg == 22) {converted_int = 16;}
  else if (msg == 23) {converted_int = 17;}
  else if (msg == 24) {converted_int = 18;}
  else if (msg == 25) {converted_int = 19;}
  else if (msg == 32) {converted_int = 20;}
  else if (msg == 33) {converted_int = 21;}
  else if (msg == 34) {converted_int = 22;}
  else if (msg == 35) {converted_int = 23;}
  else if (msg == 36) {converted_int = 24;}
  else if (msg == 37) {converted_int = 25;}
  else if (msg == 38) {converted_int = 26;}
  else if (msg == 39) {converted_int = 27;}
  else if (msg == 40) {converted_int = 28;}
  else if (msg == 41) {converted_int = 29;}
  else if (msg == 48) {converted_int = 30;}
  else if (msg == 49) {converted_int = 31;}
  else if (msg == 50) {converted_int = 32;}
  else if (msg == 51) {converted_int = 33;}
  else if (msg == 52) {converted_int = 34;}
  else if (msg == 53) {converted_int = 35;}
  else if (msg == 54) {converted_int = 36;}
  else if (msg == 55) {converted_int = 37;}
  else if (msg == 56) {converted_int = 38;}
  else if (msg == 57) {converted_int = 39;}
  else if (msg == 64) {converted_int = 40;}
  else if (msg == 65) {converted_int = 41;}
  else if (msg == 66) {converted_int = 42;}
  else if (msg == 67) {converted_int = 43;}
  else if (msg == 68) {converted_int = 44;}
  else if (msg == 69) {converted_int = 45;}
  else if (msg == 70) {converted_int = 46;}
  else if (msg == 71) {converted_int = 47;}
  else if (msg == 72) {converted_int = 48;}
  else if (msg == 73) {converted_int = 49;}
  else if (msg == 80) {converted_int = 50;}
  else if (msg == 81) {converted_int = 51;}
  else if (msg == 82) {converted_int = 52;}
  else if (msg == 83) {converted_int = 53;}
  else if (msg == 84) {converted_int = 54;}
  else if (msg == 85) {converted_int = 55;}
  else if (msg == 86) {converted_int = 56;}
  else if (msg == 87) {converted_int = 57;}
  else if (msg == 88) {converted_int = 58;}
  else if (msg == 89) {converted_int = 59;}
  else if (msg == 96) {converted_int = 60;}
  else if (msg == 97) {converted_int = 61;}
  else if (msg == 98) {converted_int = 62;}
  else if (msg == 99) {converted_int = 63;}
  else if (msg == 100) {converted_int = 64;}
  else if (msg == 101) {converted_int = 65;}
  else if (msg == 102) {converted_int = 66;}
  else if (msg == 103) {converted_int = 67;}
  else if (msg == 104) {converted_int = 68;}
  else if (msg == 105) {converted_int = 69;}
  else if (msg == 112) {converted_int = 70;}
  else if (msg == 113) {converted_int = 71;}
  else if (msg == 114) {converted_int = 72;}
  else if (msg == 115) {converted_int = 73;}
  else if (msg == 116) {converted_int = 74;}
  else if (msg == 117) {converted_int = 75;}
  else if (msg == 118) {converted_int = 76;}
  else if (msg == 119) {converted_int = 77;}
  else if (msg == 120) {converted_int = 78;}
  else if (msg == 121) {converted_int = 79;}
  else if (msg == 128) {converted_int = 80;}
  else if (msg == 129) {converted_int = 81;}
  else if (msg == 130) {converted_int = 82;}
  else if (msg == 131) {converted_int = 83;}
  else if (msg == 132) {converted_int = 84;}
  else if (msg == 133) {converted_int = 85;}
  else if (msg == 134) {converted_int = 86;}
  else if (msg == 135) {converted_int = 87;}
  else if (msg == 136) {converted_int = 88;}
  else if (msg == 137) {converted_int = 89;}
  else if (msg == 144) {converted_int = 90;}
  else if (msg == 145) {converted_int = 91;}
  else if (msg == 146) {converted_int = 92;}
  else if (msg == 147) {converted_int = 93;}
  else if (msg == 148) {converted_int = 94;}
  else if (msg == 149) {converted_int = 95;}
  else if (msg == 150) {converted_int = 96;}
  else if (msg == 151) {converted_int = 97;}
  else if (msg == 152) {converted_int = 98;}
  else if (msg == 153) {converted_int = 99;}
  else {converted_int = 0;}

  return converted_int;
}